### ISSUE TITLE
getdown.txt

### ISSUE THREAD

**Issue by gayfaggotbanannaman** [quanticc/lawena-recording-tool#121] opened 2018-07-14 20:31 UTC
the application failed to launch due to a missing resource:
http://dl.dropboxusercontent.com/u/74380/lwrt/v4.1.x/stable/latest/getdown.txt

please visit
for information on how to handle such problems

**Comment by quanticc** [comment] 2018-07-14 21:20
I moved away from Dropbox last year so that link has been broken since. You need to download the latest version from https://github.com/quanticc/lawena-recording-tool/releases

Duplicate of #94

**Closed by quanticc** 2018-07-14 21:20 UTC
Labels: duplicate

**Comment by gayfaggotbanannaman** [comment] 2018-07-15 14:51
I did download the latest version this error was found on the latest
patches installation of lawena and avoids the system from updating
